pipeline {
  agent {
    any
  }
  environment {
    AWS_ACCOUNT_ID = "${env.AWS_ACCOUNT_ID}"
    AWS_REGION = "${env.AWS_REGION ?: 'us-east-1'}"
    ORDER_REPO = "order-service"
    STORAGE_REPO = "storage-service"
    TF_DIR = "terraform"
  }
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Node Build & Test') {
      steps {
        dir('services/order-service') {
          sh 'npm ci'
          sh 'npm test'
        }
        dir('services/storage-service') {
          sh 'npm ci'
          sh 'npm test'
        }
      }
    }

    stage('Publish Test Results') {
      steps {
        script {
          // publish JUnit results generated by jest-junit
          junit 'services/**/test-results/*.xml'
          archiveArtifacts artifacts: 'services/**/test-results/*.xml', allowEmptyArchive: true
        }
      }
    }

    stage('Sonar Scan') {
      steps {
        echo 'Run Sonar scanner for both services (requires SONAR_HOST_URL and SONAR_LOGIN env vars)'
        withEnv(["SONAR_HOST_URL=${env.SONAR_HOST_URL}", "SONAR_LOGIN=${env.SONAR_LOGIN}"]) {
          sh 'sonar-scanner -Dsonar.projectKey=order-service -Dsonar.sources=services/order-service -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN'
          sh 'sonar-scanner -Dsonar.projectKey=storage-service -Dsonar.sources=services/storage-service -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN'
        }
      }
    }

    stage('Docker Build') {
      steps {
        script {
          env.SHORT_SHA = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
          env.ORDER_IMAGE_DEV = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ORDER_REPO}:dev-${SHORT_SHA}"
          env.STORAGE_IMAGE_DEV = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${STORAGE_REPO}:dev-${SHORT_SHA}"
        }
        sh 'docker build -t $ORDER_IMAGE_DEV services/order-service'
        sh 'docker build -t $STORAGE_IMAGE_DEV services/storage-service'
      }
    }

    stage('Trivy Scan') {
      steps {
        sh 'trivy image --severity HIGH,CRITICAL $ORDER_IMAGE_DEV || true'
        sh 'trivy image --severity HIGH,CRITICAL $STORAGE_IMAGE_DEV || true'
      }
    }

    stage('Push to ECR') {
      steps {
        withEnv(["AWS_DEFAULT_REGION=${AWS_REGION}"]) {
          sh '''#!/bin/bash
set -e
aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
aws ecr create-repository --repository-name ${ORDER_REPO} || true
aws ecr create-repository --repository-name ${STORAGE_REPO} || true
docker push $ORDER_IMAGE_DEV
docker push $STORAGE_IMAGE_DEV
'''
        }
      }
    }

    stage('Checkov Terraform Scan') {
      steps {
        sh 'checkov -d terraform || true'
      }
    }

    stage('Deploy Dev (Terraform)') {
      steps {
        dir('terraform/dev') {
          sh '''#!/bin/bash
export TF_VAR_order_image=$ORDER_IMAGE_DEV
export TF_VAR_storage_image=$STORAGE_IMAGE_DEV
export TF_VAR_admin_token=$ADMIN_TOKEN
terraform init -input=false
terraform apply -auto-approve -var "order_image=$ORDER_IMAGE_DEV" -var "storage_image=$STORAGE_IMAGE_DEV"
'''
        }
      }
    }

    stage('Integration Tests (Dev)') {
      steps {
        script {
          echo 'Running integration tests against dev ALB'
          env.ALB_DNS = sh(script: 'cd terraform/dev && terraform output -raw alb_dns_name', returnStdout: true).trim()
        }
        sh '''#!/bin/bash
set -euo pipefail
ALB=${ALB_DNS}
echo "ALB=${ALB}"
chmod +x tests/integration/dev_integration_test.sh || true
tests/integration/dev_integration_test.sh "${ALB}" "${ADMIN_TOKEN}"
'''
      }
    }

    stage('Create Prod Image') {
      steps {
        script {
          env.ORDER_IMAGE_PROD = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ORDER_REPO}:prod-${SHORT_SHA}"
          env.STORAGE_IMAGE_PROD = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${STORAGE_REPO}:prod-${SHORT_SHA}"
        }
        sh '''#!/bin/bash
docker tag $ORDER_IMAGE_DEV $ORDER_IMAGE_PROD
docker tag $STORAGE_IMAGE_DEV $STORAGE_IMAGE_PROD
aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
docker push $ORDER_IMAGE_PROD
docker push $STORAGE_IMAGE_PROD
'''
      }
    }

    stage('Deploy Prod (Terraform)') {
      steps {
        dir('terraform/prod') {
          sh '''#!/bin/bash
export TF_VAR_order_image=$ORDER_IMAGE_PROD
export TF_VAR_storage_image=$STORAGE_IMAGE_PROD
export TF_VAR_admin_token=$ADMIN_TOKEN
terraform init -input=false
terraform apply -auto-approve -var "order_image=$ORDER_IMAGE_PROD" -var "storage_image=$STORAGE_IMAGE_PROD"
'''
        }
      }
    }
  }

  post {
    always { echo 'Pipeline finished' }
  }
}
